dist: bionic

sudo: required

language: minimal

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install make m4
  - make
  - make test_iso

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
   - "buster-server.iso"
   - "buster-standard.iso"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

