trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 180
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - checkout: self
    submodules: true
  - bash: make
  - bash: make test_iso
  - bash: make test_ansible

